#!/bin/bash


buff=( optimal )
mp=(m)
min=(0.1 0.7 1.3 1.9 2.5 3.1 3.7 4.3 4.9)
max=(2.1 2.7 3.3 3.9 4.5 5.1 5.7 6.3 6.9)
flows=(1 2 3 4 5 ) 
try=(1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20)
codec=(G.711 GSM.AMR G.723.1)

count=0

setdest=~/ns-allinone-2.34/ns-2.34/indep-utils/cmu-scen-gen/setdest/setdest

#####

for i in "${mp[@]}"
do
        for j in "${min[@]}"
        do  
                for k in "${try[@]}"
                do  
                                for w in "${buff[@]}"
                                do  
    
                                        for z in "${codec[@]}"
                                        do  
						for q in "${flows[@]}"
                                                do
							echo "##"
	                                                echo " #  ns main.tcl $j $k $w $z $q  # "
        	                                        echo "##"
                	                                ns main.tcl $j $k $w $z $q
						done
                                        done
                                done

                done
                count=$(($count+1))
        done
done

